Update packages related to requests
Pegleg Promenade Deckhand and Shipyard should all use same versions
of packages when able.  Requests currently is giving a warning
in Pegleg:
ERROR: deckhand 0.0.1.dev657 has requirement urllib3==1.24, but
you'll have urllib3 1.24.3 which is incompatible.

Change-Id: Icdd5c687bb7072bd479107fa9a6f80a0fe1284e9